// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ9hU4UMdP6LGJgKxkuhUcWeS0toQ4HqY',
    appId: '1:1049676598289:web:3cfd838df787525496f5b0',
    messagingSenderId: '1049676598289',
    projectId: 'jwt-auth-782ea',
    authDomain: 'jwt-auth-782ea.firebaseapp.com',
    storageBucket: 'jwt-auth-782ea.firebasestorage.app',
    measurementId: 'G-RNZQ85STKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeZ-cuY-jXHbD8Kyd8aRHi9YmN5j1-QNQ',
    appId: '1:1049676598289:android:df362d679d1fec2396f5b0',
    messagingSenderId: '1049676598289',
    projectId: 'jwt-auth-782ea',
    storageBucket: 'jwt-auth-782ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Uwm1MR6WD9LTHqH3_9Gcs9sQlbtXV6o',
    appId: '1:1049676598289:ios:8e7beba7b5b8d9f696f5b0',
    messagingSenderId: '1049676598289',
    projectId: 'jwt-auth-782ea',
    storageBucket: 'jwt-auth-782ea.firebasestorage.app',
    iosClientId: '1049676598289-760au5n7c04go99ccd5s491o9ltqqdvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gogobusapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Uwm1MR6WD9LTHqH3_9Gcs9sQlbtXV6o',
    appId: '1:1049676598289:ios:8e7beba7b5b8d9f696f5b0',
    messagingSenderId: '1049676598289',
    projectId: 'jwt-auth-782ea',
    storageBucket: 'jwt-auth-782ea.firebasestorage.app',
    iosClientId: '1049676598289-760au5n7c04go99ccd5s491o9ltqqdvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gogobusapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ9hU4UMdP6LGJgKxkuhUcWeS0toQ4HqY',
    appId: '1:1049676598289:web:80cabdc49e0e8e4096f5b0',
    messagingSenderId: '1049676598289',
    projectId: 'jwt-auth-782ea',
    authDomain: 'jwt-auth-782ea.firebaseapp.com',
    storageBucket: 'jwt-auth-782ea.firebasestorage.app',
    measurementId: 'G-LRYMVSC5R7',
  );
}
